# Server settings
server:
  port: 8080           # Spring Boot will listen here in dev

# Spring & Data/JPA configuration
spring:
  datasource:
    # Local MySQL running via Docker compose (maps 3307 ? 3307)
    url: jdbc:mysql://localhost:3307/learning?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: app      # from docker-compose.yml
    password: app      # from docker-compose.yml

  jpa:
    hibernate:
      ddl-auto: validate   # Do NOT auto-create/alter tables; use Flyway instead
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect  # SQL dialect for MySQL 8

  # === Flyway migrations ===
  flyway:
    url: jdbc:mysql://localhost:3307/learning?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    user: app
    password: app
    enabled: true
    locations: classpath:db/schema,classpath:db/seed-dev   # # Run schema + dev seed when running the app normally

# === Actuator (health, info, etc.) ===
management:
  endpoints:
    web:
      exposure:
        include: health, info   # Expose /actuator/health and /actuator/info for quick liveness checks

info:
  app:
    name: "Learning Platform API"
    build: "1.0.0"

# --- Optional: can add these later when needed ---
security:
  jwt:
    secret: ${JWT_SECRET}  # JWT secret key (use a strong random key in production)
    issuer: "learning-platform"
    accessTokenTtlMinutes: 60
#
stripe:
  secretKey: ${STRIPE_SECRET_KEY}  # Stripe test secret key (never commit real keys)
  webhookSecret: ${STRIPE_WEBHOOK_SECRET} # Stripe webhook signing secret (never commit real keys)
# # Use only test mode keys in development. Never hardcode or commit production secrets.
# spring:
#   datasource:
#     # Example for using a different port if 3306 conflicts:
#     url: jdbc:mysql://localhost:3307/learning?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC

logging:
  level:
    root: INFO

# Add this section to make CORS allowed origins configurable
app:
  cors:
    allowed-origins: "http://localhost:5173"
